version: '2'

services:
  edge-impulse:
    build: ./ei
    privileged: true
    ports:
      - "80:80"
  cam:
    build: ./cam
    privileged: true
    volumes:
      - "bdi_storage:/app/storage" # Storage for the File Manager. See docs for more info.
  
  webserver:
    build: ./webserver
    ports:
      - "8080:80"
    volumes:
      -  'bdi_storage:/app/storage'
      
volumes:
  bdi_storage:

